DROP DATABASE IF EXISTS GPlayer;

CREATE DATABASE GPlayer;

USE GPlayer;

CREATE TABLE Genero (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL DEFAULT '' UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE Album (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL DEFAULT '',
    FechaPublicacion DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Playlist (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL DEFAULT '' UNIQUE,
    FechaCreacion DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Artista (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL DEFAULT '' UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE Cancion (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    AlbumID INT UNSIGNED,
    GeneroID INT UNSIGNED,
    Nombre VARCHAR(50) NOT NULL DEFAULT '',
    FechaPublicacion DATE NOT NULL,
    Path VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
    Duracion INT UNSIGNED NOT NULL,
    Favorito BOOL NOT NULL DEFAULT FALSE,
    Reproducciones INT UNSIGNED DEFAULT 0,
    PRIMARY KEY (ID),
    CONSTRAINT FK_Cancion_Album FOREIGN KEY (AlbumID) REFERENCES Album(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_Cancion_Genero FOREIGN KEY (GeneroID) REFERENCES Genero(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Artista_Album (
    ArtistaID INT UNSIGNED NOT NULL,
    AlbumID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ArtistaID, AlbumID),
    CONSTRAINT FK_Artista_Album_Artista FOREIGN KEY (ArtistaID) REFERENCES Artista(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_Artista_Album_Album FOREIGN KEY (AlbumID) REFERENCES Album(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Cancion_Artista (
    CancionID INT UNSIGNED NOT NULL,
    ArtistaID INT UNSIGNED NOT NULL,
    PRIMARY KEY (CancionID, ArtistaID),
    CONSTRAINT FK_Cancion_Artista_Cancion FOREIGN KEY (CancionID) REFERENCES Cancion(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_Cancion_Artista_Artista FOREIGN KEY (ArtistaID) REFERENCES Artista(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Cancion_Playlist (
    CancionID INT UNSIGNED NOT NULL,
    PlaylistID INT UNSIGNED NOT NULL,
    Posicion INT UNSIGNED NOT NULL,
    FechaAdicion DATETIME NOT NULL
);
